### ISSUE TITLE
Horse Breeding has some issues

### ISSUE THREAD

**Issue by CelinSilver** [Unchained-RP/bugs#30] opened 2022-05-01 22:11 UTC
Settings file:
Horses are aging -> But ingame they do not
Horses do not get unfertile by breeding -> But ingame they do

Horses should breed in 30 min -> that works

**Comment by NeonOdyssey** [comment] 2022-05-01 22:27
Duplicate of #28

**Closed** 2022-05-01 22:27 UTC
Labels: Duplicate
