### ISSUE TITLE
Harvesting Tobacco does nothing

### ISSUE THREAD

**Issue by FarFetchedNews0207** [Unchained-RP/bugs#84] opened 2022-05-12 21:52 UTC
When you fully grow and harvest a tobacco plant it does not give you anything.

### Steps to reproduce:
1. Plant tobacco
2. Grow tobacco
3. Harvest Tobacco

#### Current behaviour (bug)
When you harvest the tobacco it does nothing

#### Expected behaviour (correct)
When you harvest tobacco you will get tobacco

#### Images or video (optional)
https://medal.tv/games/red-dead-2/clips/kMdOCA6Fu6Yxb/d1337sZsFHeq?invite=cr-MSwyUGYsNjc1ODgwNTks

#### Reported by
Far#6451

**Comment by NeonOdyssey** [comment] 2022-05-12 22:22
Duplicate of #72

**Closed as completed by NeonOdyssey** 2022-05-12 22:22 UTC
Labels: Duplicate
